# Standards: 0.1
---
- name: Fact keepingyouawake user
  set_fact:
    keepingyouawake_user: "{{ keepingyouawake_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - keepingyouawake

- become: "{{ (keepingyouawake_user != ansible_user_id) | bool }}"
  become_user: "{{ keepingyouawake_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: keepingyouawake
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - keepingyouawake

- name: Remove quarantine flag
  register: keepingyouawake_quarantine
  failed_when: keepingyouawake_quarantine.rc != 0 and "No such xattr" not in keepingyouawake_quarantine.stderr
  changed_when: keepingyouawake_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/KeepingYouAwake.app
  tags:
    - keepingyouawake

...
